name: easel_dart
version: 0.1.2
author: Federico Omoto <federico.omoto@gmail.com>
description: A port of the EaselJS library to Dart.
homepage: https://github.com/FedeOmoto/EaselDart
environment:
  sdk: '>=1.4.0'
dependencies:
  browser: '>=0.10.0 <=0.11.0'
  create_dart: '>=0.1.10 <0.2.0'
